build:
    dependencies:
        before:
            - npm install istanbul   # or add it as part of your package.json

    tests:
        override:
            -
                command: 'istanbul cover --report clover test/basic/*.spec.js'
                coverage:
                    file: 'coverage/clover.xml'
                    format: 'clover'
