language: node_js
node_js:
    - "0.12"
addons:
  sauce_connect: true
before_install:
    - export DISPLAY=:99.0
    - sh -e /etc/init.d/xvfb start
env:
  global:
    - SAUCE_USERNAME=denimar
    - SAUCE_ACCESS_KEY=dm90460
before_script:
    - npm install
    - npm install -g protractor
    - webdriver-manager update
    - webdriver-manager start
script: protractor protracto-conf.js
