sudo: false
language: node_js
node_js:
  - stable
before_install:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
script:
  - "echo >> UNIT TESTS **************************************************"
  - npm run test-unit-ci
branches:
  only:
    - master
